# Generated by Django 2.1.3 on 2018-11-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('product_name', models.CharField(max_length=200)),
                ('mrp', models.CharField(max_length=10)),
                ('selling_price', models.CharField(max_length=10)),
            ],
        ),
    ]
