# Generated by Django 2.1.3 on 2018-11-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='brand',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
